name: Public Frontend CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
          port: 22
          script: |
            cd /var/www/cvehak.com
            ${{ secrets.CMD }} main

            pnpm install
            pnpx prisma generate
            pnpx prisma migrate deploy
            pnpm build
            pm2 restart "cvehak"
            pm2 restart "cvehak-workers"
